#!/bin/bash

IFS=$'\n'

source batch-vars

function runsim {
	rm SavedFiles/pair*.dat > /dev/null 2>&1
	rm SavedFiles/pref*.dat > /dev/null 2>&1
	rm SavedFiles/*.log > /dev/null 2>&1
	rm SavedFiles/bestIndividuals/* > /dev/null 2>&1
	sleep 1
	./run $1 $2;
	sleep $RUNLENGTH && killall $M3 && sleep 5s;
	if [ $1 -eq 1 ] || [ $1 -eq 3 ]; then
		killall $M3_OPPOSING && sleep 5s;
	fi
	if [ `ps aux | grep $M3 | wc -l` -gt 1 ]; then
		echo "Sorry, I couldn't kill IT..."
		exit 1
	fi

	echo -n "Stopping mlservers ... "
	timeout 1 cat mlserver/output0 > /dev/null
	echo "exit" > mlserver/input0
	echo -n "0 "
	timeout 1 cat mlserver/output1 > /dev/null
	echo "exit" > mlserver/input1
	echo -n "1 "
	timeout 1 cat mlserver/output2 > /dev/null
	echo "exit" > mlserver/input2
	echo "2 - done"
}

function makedir {
	mkdir $1 > /dev/null 2>&1
}

function runallied {
	echo "${ARCH}/tau_${1}_a/${2}..."
	makedir "${ARCH}/tau_${1}_a"
	runsim 0 $1
	cp -a ./SavedFiles ${ARCH}/tau_${1}_a/${2}
}

function runopposing {
	echo "${ARCH}/tau_${1}_o/${2}..."
	makedir "${ARCH}/tau_${1}_o"
	runsim 1 $1
	cp -a ./SavedFiles ${ARCH}/tau_${1}_o/${2}
}

function runsingle {
	echo "${ARCH}/tau_${1}_s/${2}..."
	makedir "${ARCH}/tau_${1}_s"
	runsim 2 $1
	cp -a ./SavedFiles ${ARCH}/tau_${1}_s/${2}
}

function runsingleopposing {
	echo "${ARCH}/tau_${1}_so/${2}..."
	makedir "${ARCH}/tau_${1}_so"
	runsim 3 $1
	cp -a ./SavedFiles ${ARCH}/tau_${1}_so/${2}
}
