#!/bin/bash

IFS=$'\n'

function runsim {
	rm SavedFiles/pair*.dat > /dev/null 2>&1
	rm SavedFiles/pref*.dat > /dev/null 2>&1
	rm SavedFiles/*.log > /dev/null 2>&1
	rm SavedFiles/bestIndividuals/* > /dev/null 2>&1
	./run $1 $2;
	sleep 1800 && killall M3 && sleep 5s;
	if [ $1 -eq 1 ]; then
		killall M3-opposing && sleep 5s;
	fi
	if [ `ps aux | grep M3 | wc -l` -gt 1 ]; then
		echo "Sorry, I couldn't kill IT..."
		exit 1
	fi
}

function makedir {
	mkdir $1 > /dev/null 2>&1
}

function runallied {
	echo "arch/tau${1}a/${2}..."
	makedir "arch/tau${1}a"
	runsim 0 $1
	cp -a ./SavedFiles ./arch/tau${1}a/${2}
}

function runopposing {
	echo "arch/tau${1}o/${2}..."
	makedir "arch/tau${1}o"
	runsim 1 $1
	cp -a ./SavedFiles ./arch/tau${1}o/${2}
}

for i in `seq -w 1 10`; do
	for nn in `seq 2 4`; do
		runallied $nn $i
	done
done
