#!/bin/bash

IFS=$'\n'
for i in `seq -w 1 10`; do
	rm SavedFiles/pair*.dat
	rm SavedFiles/pref*.dat
	rm SavedFiles/*.log
	./run 0 3;
	sleep 1h && killall M3 && sleep 5s;
#	killall M3-opposing && sleep 5s;
	if [ `ps aux | grep M3 | wc -l` -gt 1 ]; then
		echo "Sorry, I couldn't kill IT..."
		exit 1
	fi
	cp -a ./SavedFiles ./arch/tau3/$i
done
